# Generated by Django 5.0.14 on 2026-05-24 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_add_saved_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed Use')], default='residential', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('sold_units', models.PositiveIntegerField(default=0)),
                ('available_units', models.PositiveIntegerField(default=0)),
                ('blocked_units', models.PositiveIntegerField(default=0)),
                ('completion_pct', models.PositiveSmallIntegerField(default=0, help_text='0–100%')),
                ('rera_id', models.CharField(blank=True, max_length=100)),
                ('is_rera_verified', models.BooleanField(default=False)),
                ('expected_possession', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='projects/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='properties.city')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='properties.locality')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
