# Generated by Django 5.0.14 on 2026-05-24 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ban_user', 'Ban User'), ('unban_user', 'Unban User'), ('impersonate', 'Impersonate User'), ('stop_impersonate', 'Stop Impersonation'), ('approve_listing', 'Approve Listing'), ('reject_listing', 'Reject Listing'), ('verify_broker', 'Verify Broker'), ('suspend_broker', 'Suspend Broker'), ('reinstate_broker', 'Reinstate Broker'), ('other', 'Other')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
